title: Steven Leathard # your name (or website title) here
logo: "/images/circlemeprof2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm currently in a data analytics group focused on healthcare data engineering 
  and visualization projects. I work with both clinical and financial customers to transform 
  data into actionable information, using a mix of SQL, Python, HTML, CSS, Bokeh, 
  Power BI, and QlikView.   
  <br><br>
  <a href="https://www.linkedin.com/in/steven-leathard-274678a">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
