title: Steven Leathard # your name (or website title) here
logo: "/images/circleme3.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p>I'm currently in a data analytics group focused on healthcare data engineering 
  and visualization projects. I work with both clinical and financial customers to transform 
  data into actionable information, using a mix of SQL, Python, Pandas, HTML, CSS, Bokeh, 
  Power BI, QlikView, and Cerner CCL.</p>
  <p>Some of my projects are listed here with descriptions and links to their repositories. All of these 
  examples are presented here with fabricated data.</p> 
  <a href="https://www.linkedin.com/in/steven-leathard-274678a">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
