title: Steven Leathard # your name (or website title) here
logo: "/images/circleme.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Engineer, Systems Analyst, BI Developer
  <br><br>
  Something something 
  <br><br>
  <a href="https://www.linkedin.com/in/steven-leathard-274678a">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
